language: r
pandoc_version: 1.17.2
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: Nj8sljbSGnF5nGpqgWm/MB3B0O5NznzNCGA9Smul0fD4CmXxjCBAZtCCY8F3sJjq9dbsFn0NHG9YXIYBGx4PGqXYrSDxRa+0gJmrys+VDihZwjeYnPZv6mCuEgTbacEcnsq1NoOsIfNKED9JdcaNsJ9qQLdAwhlMrYmgPIORPtZv42jNu83NwX6CLwJr0obo4D+XWyaUMiAj+i8TzWtmhQctiImeBtfixNSAGA2o3Ru3VLpEcrLvX/lLwIGNFyEx+RdLE9upL1USjZ/pJdYfjQWpnvSo0yCZg/+wjpXLuAYmEvHY63WLoK0ijLGcuZsSUHcybplUw+8/3Ilk+XYRqkvV4Z4LQ2gW0ugK6y+jQ6XuNInspd1oWdPF2zWxvowp07Cifww7fHZEN3MUtOwXJkf3yLeNbxQMUy7y9tdci4y+zrnzEPwwNFli4zE0APoQBY/tgAm6W+aq9stmb+YerzLnUvuLic6MV2famlbKf4gC5xl0W5qt9xYYWgsSIYTOF0bav97IMhMeK6rbSkrgA5te9l3EVkSv6LV/vWeLnI/lSteYPK5ov7IBGhwNnZc8sPH1lMMmw/Qod9Lay1g1CEdSn+2wZthbJFJNDIWWvr2DpS/kbsIqiEsT4BZN4HUqtinei7MKSFls34XkzBAlAtXYHGRU5TKjoCRT2xW3vq0=
