language: r
pandoc_version: 1.17.2
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: FWm9JmZumYaqmDKMMyyAhnjWT7+lWO4LPAoLfmOARo98l9Ot6da4et39InocpgQgK28oqdbRG79WCM4ZGIDnB5aj9Dw92nQoBpijIUKM8923t7KpnzNyxUjPAqg6jXmTBzPZXmjlmcfMiaiZzF9unCVOXPJRN9maOxbHi6YiqrvQSANcEApHqbFjTFeFE/9zyNx+Kmlb+zS7SNCUsiGfpWE8XR2O4w0sxL09wQ79JohMA4/VdhSQRT9Q4IIdsGVX253CjETZNsfNZM+mrg980UiFrXVT2jpinmf245dw4rSjo/qxVnArN4liMNiW/rEyx4ZWMZx3jAd7+xOYti6X8Yny8OacA+TY0QRhWOiKnlMy3TYrVquS5ASAfUE44H3QxuLPHeUz5u2IrVa6kCICsBDpXGyBI/Uzdpshnl/kQh6wT/Vd9CRE9alZtexLodKZyKWCrbfQRrW6+k4Un74QkrzBpOTKl2vEUBrSKXF3DScg3eTpc3boXCzWWmip2fM1R3CrpWCZAvGhc01sZlCq6dAuSFdwrClnd8v0fjnqN3gCuzHSltXw0wnFZ1qQ9KRniJJ2k1rXAxiNfYXs5f5FZAT12TzZ9NeqH070Cs0sPW4epPFnbkbYkT6Nknrd9k7e87HZ/l7IFkZcFsZWjWruW7tUVVhZmvVjnWkme1fi6VY=
