language: r
pandoc_version: 1.17.2
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: GBF3Q86WMevMExkbFEAONqR8qgIkd1CbM3wHe2Gp+m1YA4flklKW0YZJ2vRyM1Scaoghio9X7XlqK1DVkMkIKndv1kezu0mHUws/jAKz7hsdbj1YH4A2/PPWXf8+Ob6jApLMMxt5Ec6qj81dpxPNHGsezmXuTyPI6wHv53J7NetGZjaWksP1edrPp19FRXNeSQRQuTI00z3YnATkZrwQ70waeelGsIWS7kbMSAiIVSF97eE/WFAufiHbXc4EeRH5HvyqesTIoJWAxvpErjQnNSH3D/nhx/ecpxLm2GSukuuL7fkMoBc9XEzt11LGRUAckiKQY3aR/5hhTUViDYnq228Ywz0HayGT6a+3V9DFgUcSOIm5L3cJB7J9Rsgg77OMIdZdrAyWg+c+nKCiq6KoNVEujkFUoDNU2PnIt/vYv6uEYdPizxv15uKCnZiD824a67NkYTZcl3dBefsGueBOosy1XEEGiYnueV5mj1wUMH7IcOWgULOeAIhS+X+shZ30Rb3SkF6Zdw5EKKXymOnWztRlBRi0iV/u9ztzuki+BUb6mCAmGJi4zuMQcDDyFRwAmLWDFxz48qGulfuVTo+9bPmyu4K6nB1dulETJy6UdKsD8MqmFF9seBFQ1LAHbs5nMBPT3ufJIlprzAhk2sBT2XGrS3bZdWmIfTnKOMoeYaI=
